### ISSUE TITLE
Issue when building ALISA

### ISSUE THREAD

**Issue by sei-jdelange** [osate/alisa#1]
when importing ALISA, I got the following error in the Eclipse error log

![alisa](https://cloud.githubusercontent.com/assets/13833784/14710720/8bf212a4-07a4-11e6-8f48-29b9862114c6.PNG)
![alisa](https://cloud.githubusercontent.com/assets/13833784/14710722/8cdbdd58-07a4-11e6-98f5-5073e11391be.PNG)

**Comment by lwrage** [comment]
Did you try to clean the projects to force a full build?
