### ISSUE TITLE
XSemantics Predicate evaluation does not work

### ISSUE THREAD

**Issue by reteprelief** [osate/alisa#16]
I get 					
"Could not evaluate value predicate: it.xsemantics.runtime.RuleFailedException: failed: InterpretBinaryExpression: [component <- SystemInstance \'SCS_tier1_Instance\', computes <- {}, element <- system SCS features power: in feature Ph..., vals <- {org.osate.reqspec.reqSpec.impl.ReqValDeclarationImpl@12d86a3e (name: MaximumWeight, range: false)=1.2 }] |- MaximumWeight == #SEI::WeightLimit ~> PropertyValue"
This occurs on the value predicate for SCS requirement R1 in the SimpleControlSystem example.
You may have to uncomment the value predicate.

**Comment by lwrage** [comment]
I noticed that yesterday. Do you know when it was still working? 
We really need unit tests for all the ALSIA stuff.

**Comment by reteprelief** [comment]
Doing checkouts from the history the problems seems to exist all the way back the the update2 release - hard to believe that this has not been noticed since then.
