### ISSUE TITLE
SpotlightUtil not found

### ISSUE THREAD

**Issue by brlarson** [osate/alisa#33]
package org.osate.reqspec.ui.handlers
can't find import on line 56
import org.osate.recspec.ui.spotlight.utils.SpotlightUtil;
which leads to a "SpotlightUtil cannot be resolved" error message on line 362

**Comment by lwrage** [comment]
My sources don't contain "Spotlight" any longer. Git pull?

**Comment by brlarson** [comment]
I re-opened the Alisa projects, I did a fresh pull of alisa develop (getting no changes), and have the same errors with SpotlightUtil in the same places.


On Nov 30, 2017, at 11:15 AM, Lutz Wrage <notifications@github.com<mailto:notifications@github.com>> wrote:


My sources don't contain "Spotlight" any longer. Git pull?

**Comment by lwrage** [comment]
Spotlight was removed on Oct 25 in commit a692c9efdb6e66c788f15658ee0a8853329e1c84
Please check your git history if it contains that commit. Are you sure you're on the develop branch?

**Comment by brlarson** [comment]
The most recent is 63bf6da from 20 days ago.  I just did another pull of develop branch with "everything up to date" response.

I threaten to give my children a software repository, instead of coal, for Christmas when they misbehave.

On Dec 4, 2017, at 8:13 AM, Lutz Wrage <notifications@github.com<mailto:notifications@github.com>> wrote:


Spotlight was removed on Oct 25 in commit a692c9e<https://github.com/osate/alisa/commit/a692c9efdb6e66c788f15658ee0a8853329e1c84>
Please check your git history if it contains that commit. Are you sure you're on the develop branch?
