### ISSUE TITLE
Property reference is not resolved in formal parameter

### ISSUE THREAD

**Issue by reteprelief** [osate/alisa#4]
The example is in SimpleControlSystem in alisa-examples.
See methodregistry in Alisa-Consistency.
// PHF LUTZ	method ConsistentVoltage (feature, voltage: Physical::Voltage_Type ) boolean 
	method ConsistentVoltage (feature, voltage: real ) boolean 
	:"Ensure Voltage property value is consistent with required voltage value" [
		java alisa_consistency.ModelVerifications.hasVoltage(String name, double voltage)
		description "Verify that the Voltage property has the same value as specified in the requirement"
	]

**Comment by reteprelief** [comment]
There is a second method that has a problem resolving property reference - in this case when declaring values to be passed as properties - is: (found in the same registry)
// PHF: property values
//	method SetGetVoltage (feature) properties(Physical::Voltage)returns (volts: real )
//	:"Ensure Voltage property value is consistent with required voltage value" [
//		java alisa_consistency.ModelVerifications.getVoltage
//		description "Verify that the Voltage property has the same value as specified in the requirement"
//	]

**Comment by lwrage** [comment]
Not a bug. Project Alisa-Consistency needs to reference project SimpleControlSystem to have access to the property set Physical which is defined there.

**Comment by reteprelief** [comment]
thanks for looking at it. Sometimes my brain is too dense :-)
