### ISSUE TITLE
Report generation does not work (SimpleControlSystem example)

### ISSUE THREAD

**Issue by paolo-crisafulli** [osate/alisa#48]
I'm trying Alisa, using Osate 2.3.2 and the SimpleControlSystem example (https://github.com/osate/alisa-examples/tree/master/SimpleControlSystem).

I'd like to generate the "Traceability" and "Requirements" reports:
- right-click on SCSgoals.goaldoc (or any goal or reqspec file), then Report Generation/Traceability results in this almost empty file:

## Stakeholder Goal to Stakeholders Report

**Project:**
*SimpleControlSystem*

- right-click on SCS.reqspec (or any reqspec file), then Report Generation/Requirements results in this almost empty file:

## System Requirements Report

**Project:**
*SimpleControlSystem*

**Comment by lwrage** [comment]
I cannot reproduce the issue. I tried the reports in the nightly build, and they work as expected.

**Comment by paolo-crisafulli** [comment]
Ok, thank you for your reply.
I downloaded today's [nightly build](https://osate-build.sei.cmu.edu/download/osate/testing/products/osate2-2.3.3-v20180419-1326-linux.gtk.x86_64.tar.gz) of Osate product and:
- the Alisa-Consistency project does not compile:
```
Description	Resource	Path	Location	Type
Issue cannot be resolved to a type	ModelVerifications.java	/Alisa-Consistency/src/alisa_consistency	line 54	Java Problem
The import org.osate.result.Issue cannot be resolved	ModelVerifications.java	/Alisa-Consistency/src/alisa_consistency	line 16	Java Problem
The method createFail(String, FeatureInstance, String) is undefined for the type ResultUtil	ModelVerifications.java	/Alisa-Consistency/src/alisa_consistency	line 54	Java Problem
The method createResult(String, ComponentInstance) is undefined for the type ResultUtil	ModelVerifications.java	/Alisa-Consistency/src/alisa_consistency	line 46	Java Problem
The method getIssues() is undefined for the type Result	ModelVerifications.java	/Alisa-Consistency/src/alisa_consistency	line 58	Java Problem
The type 'alisa_consistency.Activator' is not on the plug-in classpath	MANIFEST.MF	/Alisa-Consistency/META-INF	line 6	Plug-in Problem
```
- the SimpleControlSystem project contains multiple errors:
```
Description	Resource	Path	Location	Type
Couldn't resolve reference to FunctionDefinition 'eightBudget'.	BudgetResolute.aadl	/SimpleControlSystem/resolute	line: 64 /SimpleControlSystem/resolute/BudgetResolute.aadl	Xtext Check (fast)
Requirement is for Flow while verification method is not for Flow	scsimplvplan.verify	/SimpleControlSystem/alisa	line: 8 /SimpleControlSystem/alisa/scsimplvplan.verify	Verify Problem
Requirement is for Flow while verification method is not for Flow	scsimplvplan.verify	/SimpleControlSystem/alisa	line: 9 /SimpleControlSystem/alisa/scsimplvplan.verify	Verify Problem
Missing claims for multiple requirements	scsimplvplan.verify	/SimpleControlSystem/alisa	line: 3 /SimpleControlSystem/alisa/scsimplvplan.verify	Verify Problem
No claim for requirement Actuator_R1	scsimplvplan.verify	/SimpleControlSystem/alisa	line: 3 /SimpleControlSystem/alisa/scsimplvplan.verify	Verify Problem
No claim for requirement DCS_R1	scsimplvplan.verify	/SimpleControlSystem/alisa	line: 3 /SimpleControlSystem/alisa/scsimplvplan.verify	Verify Problem
No claim for requirement Sensor1_R1	scsimplvplan.verify	/SimpleControlSystem/alisa	line: 3 /SimpleControlSystem/alisa/scsimplvplan.verify	Verify Problem
No claim for requirement Sensor2_R1	scsimplvplan.verify	/SimpleControlSystem/alisa	line: 3 /SimpleControlSystem/alisa/scsimplvplan.verify	Verify Problem
```
Any advice?
Thank you in advance.

**Comment by paolo-crisafulli** [comment]
I also tried the report generation, and the output is still almost empty.
[reqs.docx](https://github.com/osate/alisa/files/1932450/reqs.docx)
[traceability.docx](https://github.com/osate/alisa/files/1932454/traceability.docx)

**Comment by lwrage** [comment]
The files you attached are not empty, e.g., reqs.docx has a table with the requirements starting on page 2.

**Comment by paolo-crisafulli** [comment]
Sorry, my bad: I had opened the files with LibreOffice only so far, and they do appear empty there.
First time I came accross such an isssue with Writer!
Thank you, bug closed.
